dist: trusty

language: java

jdk:
  - oraclejdk8

# Run on container-based infrastructure
sudo: false

cache:
  directories:
    - ${HOME}/.m2

before_install:
  - if [ ! -z "${GPG_SECRET_KEYS}" ]; then echo ${GPG_SECRET_KEYS} | base64 --decode | ${GPG_EXECUTABLE} --import; fi
  - if [ ! -z "${GPG_OWNERTRUST}" ]; then echo ${GPG_OWNERTRUST} | base64 --decode | ${GPG_EXECUTABLE} --import-ownertrust; fi

install:
  - mvn --quiet --settings .travis/settings.xml dependency:resolve
  - mvn --quiet --settings .travis/settings.xml dependency:resolve-plugins

script:
  - mvn -T 2.0C --batch-mode --settings .travis/settings.xml --show-version test

deploy:
  - provider: script
    script: .travis/deploy-lib.sh .travis/settings.xml
    skip_cleanup: true
    on:
      repo: spals/parent-pom
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: .travis/deploy-lib.sh .travis/settings.xml
    skip_cleanup: true
    on:
      repo: spals/parent-pom
      tags: true
      jdk: oraclejdk8
